[conjure-auto-repl] Cleanup .nrepl-port on exit
Otherwise we end up with stale .nrepl-port files lying around which is
annoying because they have to be cleaned up in order for the auto-repl
to start properly again.

diff --git a/local/bin/conjure-auto-repl b/local/bin/conjure-auto-repl
--- a/local/bin/conjure-auto-repl
+++ b/local/bin/conjure-auto-repl
@@ -2,8 +2,11 @@
 
 export AWS_PROFILE=${AWS_PROFILE:-personal}
 
+# trap exist and cleanup .nrepl-port
+trap "rm -f .nrepl-port" EXIT
+
 if [ -e node_modules/.bin/nbb ]; then
-  exec ./node_modules/.bin/nbb nrepl-server :port 8794 
+  ./node_modules/.bin/nbb -cp src:src/cljs nrepl-server :port 8794 
 else
-  exec bb nrepl-server localhost:8794
+  bb nrepl-server localhost:8794
 fi
